# headless service to avoid deletion of patroni-pg11-config endpoint
apiVersion: v1
kind: Service
metadata:
  name: patroni-pg11-config
  labels:
    application: patroni
    cluster-name: patroni-pg11
spec:
  clusterIP: None

---
apiVersion: v1
kind: Endpoints
metadata:
  name: &cluster_name patroni-pg11
  labels:
    application: patroni
    cluster-name: *cluster_name
subsets: []

---
apiVersion: v1
kind: Service
metadata:
  name: &cluster_name patroni-pg11
  labels:
    application: patroni
    cluster-name: *cluster_name
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: patroni-pg11-repl
  labels:
    application: patroni
    cluster-name:  &cluster_name patroni-pg11
    role: replica
spec:
  type: ClusterIP
  selector:
    application: patroni
    cluster-name: *cluster_name
    role: replica
  ports:
  - port: 5432
    targetPort: 5432
