apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoready
  labels:
    app: photoready
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoready
  template:
    metadata:
      labels:
        app: photoready
    spec:

      initContainers:
      - name: copy
        image: photoready
        imagePullPolicy: IfNotPresent
        command:
          - bash
          - -c
          - "cp -r /flyway/jars/* /dest-flyway-jars"
        volumeMounts:
        - name: lib-content
          mountPath: /dest-flyway-jars

      - name: flyway
        image: flyway/flyway:8.0.3
        imagePullPolicy: IfNotPresent
        args:
        - migrate
        volumeMounts:
        - name: flyway-conf
          mountPath: /flyway/conf
        - name: lib-content
          mountPath: /flyway/jars
        - name: flyway-sql
          mountPath: /flyway/sql
        env:
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: photoready.acid-photoready.credentials.postgresql.acid.zalan.do 
              key: password

      - name: flyway-info
        image: flyway/flyway:8.0.3
        imagePullPolicy: IfNotPresent
        args:
        - info
        volumeMounts:
        - name: flyway-conf
          mountPath: /flyway/conf
        - name: lib-content
          mountPath: /flyway/jars
        - name: flyway-sql
          mountPath: /flyway/sql
        env:
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: photoready.acid-photoready.credentials.postgresql.acid.zalan.do 
              key: password

      containers:
      - name: photoready
        image: photoready
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        env:
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: photoready.acid-photoready.credentials.postgresql.acid.zalan.do 
              key: password
        ports:
          - containerPort: 80

      volumes:
      - name: lib-content
        emptyDir: {}
      - name: flyway-conf
        configMap:
          name: flyway-conf
      - name: flyway-jars
        configMap:
          name: flyway-jars
      - name: flyway-sql
        configMap:
          name: flyway-sql
