apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../components/redis

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
  - name: nginx-conf
    files:
      - nginx.conf
