apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- ../components/redis

configMapGenerator:
- files:
  - flyway/conf/flyway.conf
  name: flyway-conf
- files:
  - flyway/sql/V1__Initial.sql
  - flyway/sql/V2__Tables.sql
  - flyway/sql/V3__PeopleData.sql
  name: flyway-sql


images:
- name: photoready
  newName: fernandogalmeida/photoready
  newTag: zSnzHgh
