apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-photoready
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    zalando:
    - superuser
    - createdb
    photoready: []
  databases:
    photoready: photoready
  preparedDatabases:
    bar: {}
  postgresql:
    version: "14"
